custom-web-service1:
  client:
    authorization:
      enable: true
      username: user
      password: changeit
    base-service-url: http://localhost:8084
    connection:
      connection-timeout: 5000
      socket-timeout: 5000

custom-web-service2:
  client:
    authorization:
      enable: true
      username: user
      password: changeit
    base-service-url: http://localhost:8084
    connection:
      connection-timeout: 5000
      socket-timeout: 5000
server:
  port: 8084